title: Shashank Upadhyay
logo: "/images/logo.png?raw=true"
description: >
  Techno-functional professional with 8+ years of experience, who loves to solve real-world business challenges using data science.
  Currently working as a Senior Data Scientist with <https://www.chubb.com/uk-en/">CHUBB</a> in driving driven decision making.
  <br><br>
  <a href="https://www.linkedin.com/in/upadhyayshashank/">Find Me On LinkedIn</a>
  <br><br>
  <a href="https://github.com/data-crat">View My GitHub</a> 
  
theme: jekyll-theme-minimal

