title: Shashank Upadhyay
logo: "/images/circle-cropped.png?raw=true"
description: >Emerging techno-functional professional with 3+ years of experience, who loves to solve real-world business challenges using data science.
  <br><br>
  Currently working  as a Data Scientist with <a href="https://www.hdfcergo.com/health-insurance">HDFC ERGO</a> in the Sales & Distribution Analytics division.
  <br><br>
  <a href="https://www.linkedin.com/in/upadhyayshashank/">Find Me On LinkedIn</a>
  <br><br>
  <a href="https://github.com/data-crat">View My GitHub</a> 
  
theme: jekyll-theme-minimal

