title: Shashank Upadhyay
logo: "/images/logo.png?raw=true"
description: > 
  Emerging techno-functional professional with 3+ years of experience, who loves to solve real-world business challenges using data science.
  <br><br>
  <a href="https://www.linkedin.com/in/upadhyayshashank/">Find Me On LinkedIn</a> 
  <a href="https://github.com/data-crat">View My GitHub</a> 
  
theme: jekyll-theme-minimal

