title: Shashank Upadhyay
logo: "/images/logo.png?raw=true"
description: >
  Techno-functional professional with 5+ years of experience, who loves to solve real-world business challenges using data science.
  Currently working as a Data Science Consultant with <a href="https://accenture.com/">Accenture</a> in BFSI.
  <br><br>
  <a href="https://www.linkedin.com/in/upadhyayshashank/">Find Me On LinkedIn</a>
  <br><br>
  <a href="https://github.com/data-crat">View My GitHub</a> 
  
theme: jekyll-theme-minimal

